name = "hammerschach-gamer-lobby"
main = "src/index.js"
compatibility_date = "2026-06-26"
keep_vars = true

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[d1_databases]]
binding = "DB"
database_name = "hammerschach-gamer-db"
database_id = "e6155132-6ad6-4569-be28-122540d3748f"